services:
  # warehouse
  postgres:
    image: postgres:16.4
    restart: always
    container_name: noth-warehouse
    environment:
      - POSTGRES_USER=overseer
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=warehouse
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # warhouse admin
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    container_name: noth-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${USER_AGENT}
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # # filestore
  # couchdb:
  #   image: couchdb:3.3.3
  #   restart: always
  #   container_name: renai-fs
  #   environment:
  #     - COUCHDB_USER=admin
  #     - COUCHDB_PASSWORD=password
  #   ports:
  #     - "5984:5984"
  #   volumes:
  #     - ./couchdb_data:/opt/couchdb/data
  #
  # # lakehouse
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
  #   restart: always
  #   container_name: noth-lake
  #   ports:
  #     - 9200:9200
  #   environment:
  #     discovery.type: 'single-node'
  #     xpack.security.enabled: 'true'
  #     ES_JAVA_OPTS: '-Xmx2g -Xms2g'
  #     ELASTIC_USERNAME: 'admin'
  #     ELASTIC_PASSWORD: 'password'
  #
  # # lakehouse admin
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.16.0
  #   restart: always
  #   container_name: noth-kibana
  #   ports:
  #     - 5601:5601
  #   environment:
  #     ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
  #
  #     ELASTICSEARCH_USERNAME: 'admin'
  #     ELASTICSEARCH_PASSWORD: 'password'
  #   depends_on:
  #     - elasticsearch

volumes:
  couchdb_data:
  postgres_data:
