services:
  couchdb:
    image: couchdb:3.3.3
    restart: always
    container_name: renai-fs
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "5984:5984"
    volumes:
      - ./couchdb_data:/opt/couchdb/data

  postgres:
    image: postgres:16.4
    restart: always
    container_name: renai-pg
    environment:
      - POSTGRES_USER=overseer
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=renai
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${USER_AGENT}
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  couchdb_data:
  postgres_data: