services:
  couchdb:
    image: couchdb:latest
    restart: always
    container_name: renai-fs
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "5984:5984"
    volumes:
      - ./couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
